FROM node

WORKDIR /usr/src

RUN apt update && apt install -y curl libcurl3 libcurl3-dev git apt-transport-https \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt update && apt install yarn \
    && yarn global add webpack nodemon cpx

CMD . ./build.sh